interface SwiperOptions {
    initialSlide?: number;
    direction?: string;
    speed?: number;
    setWrapperSize?: boolean;
    virtualTranslate?: boolean;
    width?: number;
    height?: number;
    autoHeight?: boolean;
    roundLengths?: boolean;
    nested?: boolean;
    autoplay?: number;
    autoplayStopOnLast?: boolean;
    autoplayDisableOnInteraction?: boolean;
    watchSlidesProgress?: boolean;
    watchSlidesVisibility?: boolean;
    freeMode?: boolean;
    freeModeMomentum?: boolean;
    freeModeMomentumRatio?: number;
    freeModeMomentumVelocityRatio?: number;
    freeModeMomentumBounce?: boolean;
    freeModeMomentumBounceRatio?: number;
    freeModeMinimumVelocity?: number;
    freeModeSticky?: boolean;
    effect?: string;
    fade?: {};
    cube?: {};
    coverflow?: {};
    flip?: {};
    parallax?: boolean;
    spaceBetween?: number;
    slidesPerView?: number | string;
    slidesPerColumn?: number;
    slidesPerColumnFill?: string;
    slidesPerGroup?: number;
    centeredSlides?: boolean;
    slidesOffsetBefore?: number;
    slidesOffsetAfter?: number;
    grabCursor?: boolean;
    touchEventsTarget?: string;
    touchRatio?: number;
    touchAngle?: number;
    simulateTouch?: boolean;
    shortSwipes?: boolean;
    longSwipes?: boolean;
    longSwipesRatio?: number;
    longSwipesMs?: number;
    followFinger?: boolean;
    onlyExternal?: boolean;
    threshold?: number;
    touchMoveStopPropagation?: boolean;
    iOSEdgeSwipeDetection?: boolean;
    iOSEdgeSwipeThreshold?: number;
    resistance?: boolean;
    resistanceRatio?: number;
    preventClicks?: boolean;
    preventClicksPropagation?: boolean;
    slideToClickedSlide?: boolean;
    allowSwipeToPrev?: boolean;
    allowSwipeToNext?: boolean;
    noSwiping?: boolean;
    noSwipingClass?: string;
    swipeHandler?: string | Element;
    uniqueNavElements?: boolean;
    pagination?: string | Element;
    paginationType?: string;
    paginationHide?: boolean;
    paginationClickable?: boolean;
    paginationElement?: string;
    paginationBulletRender?(swiper: Swiper, index: number, className: string): void;
    paginationFractionRender?(swiper: Swiper, currentClassName: string, totalClassName: string): void;
    paginationProgressRender?(swiper: Swiper, progressbarClass: string): void;
    paginationCustomRender?(swiper: Swiper, current: number, total: number): void;
    nextButton?: string | Element;
    prevButton?: string | Element;
    scrollbar?: string | Element | SwiperScrollbarOptions;
    scrollbarHide?: boolean;
    scrollbarDraggable?: boolean;
    scrollbarSnapOnRelease?: boolean;
    a11y?: boolean;
    prevSlideMessage?: string;
    nextSlideMessage?: string;
    firstSlideMessage?: string;
    lastSlideMessage?: string;
    paginationBulletMessage?: string;
    keyboardControl?: boolean;
    mousewheelControl?: boolean;
    mousewheelForceToAxis?: boolean;
    mousewheelReleaseOnEdges?: boolean;
    mousewheelInvert?: boolean;
    mousewheelSensitivity?: number;
    hashnav?: boolean;
    hashnavWatchState?: boolean;
    history?: string;
    preloadImages?: boolean;
    updateOnImagesReady?: boolean;
    lazyLoading?: boolean;
    lazyLoadingInPrevNext?: boolean;
    lazyLoadingInPrevNextAmount?: number;
    lazyLoadingOnTransitionStart?: boolean;
    loop?: boolean;
    loopAdditionalSlides?: number;
    loopedSlides?: number;
    zoom?: boolean;
    control?: Swiper;
    controlInverse?: boolean;
    controlBy?: string;
    observer?: boolean;
    observeParents?: boolean;
    breakpoints?: {};
    runCallbacksOnInit?: boolean;
    onInit?(swiper: Swiper): void;
    onSlideChangeStart?(swiper: Swiper): void;
    onSlideChangeEnd?(swiper: Swiper): void;
    onSlideNextStart?(swiper: Swiper): void;
    onSlideNextEnd?(swiper: Swiper): void;
    onSlidePrevStart?(swiper: Swiper): void;
    onSlidePrevEnd?(swiper: Swiper): void;
    onTransitionStart?(swiper: Swiper): void;
    onTransitionEnd?(swiper: Swiper): void;
    onTouchStart?(swiper: Swiper, event: Event): void;
    onTouchMove?(swiper: Swiper, event: Event): void;
    onTouchMoveOpposite?(swiper: Swiper, event: Event): void;
    onSliderMove?(swiper: Swiper, event: Event): void;
    onTouchEnd?(swiper: Swiper, event: Event): void;
    onClick?(swiper: Swiper, event: Event): void;
    onTap?(swiper: Swiper, event: Event): void;
    onDoubleTap?(swiper: Swiper, event: Event): void;
    onImagesReady?(swiper: Swiper): void;
    onProgress?(swiper: Swiper, progress: number): void;
    onReachBeginning?(swiper: Swiper): void;
    onReachEnd?(swiper: Swiper): void;
    onDestroy?(swiper: Swiper): void;
    onSetTranslate?(swiper: Swiper, translate: any): void;
    onSetTransition?(swiper: Swiper, transition: any): void;
    onAutoplay?(swiper: Swiper): void;
    onAutoplayStart?(swiper: Swiper): void;
    onAutoplayStop?(swiper: Swiper): void;
    onLazyImageLoad?(swiper: Swiper, slide: any, image: any): void;
    onLazyImageReady?(swiper: Swiper, slide: any, image: any): void;
    onPaginationRendered?(swiper: Swiper, paginationContainer: any): void;
    onScroll?(swiper: Swiper, event: Event): void;
    onBeforeResize?(swiper: Swiper): void;
    onAfterResize?(swiper: Swiper): void;
    onKeyPress?(swiper: Swiper, kc: any): void;
    slideClass?: string;
    slideActiveClass?: string;
    slideVisibleClass?: string;
    slideDuplicateClass?: string;
    slideNextClass?: string;
    slidePrevClass?: string;
    wrapperClass?: string;
    bulletClass?: string;
    bulletActiveClass?: string;
    paginationHiddenClass?: string;
    paginationCurrentClass?: string;
    paginationTotalClass?: string;
    paginationProgressbarClass?: string;
    buttonDisabledClass?: string;
}
interface SwiperScrollbarOptions {
    container: string;
    draggable?: boolean;
    hide?: boolean;
    snapOnRelease?: boolean;
}
declare class SwiperSlide {
    append(): SwiperSlide;
    clone(): SwiperSlide;
    getWidth(): number;
    getHeight(): number;
    getOffset(): {
        top: number;
        left: number;
    };
    insertAfter(index: number): SwiperSlide;
    prepend(): SwiperSlide;
    remove(): void;
}
declare class Swiper {
    constructor(container: string | Element, options?: SwiperOptions);
    width: number;
    height: number;
    params: any;
    positions: any;
    wrapper: any;
    virtualSize: number;
    support: {
        touch: boolean;
        transforms: boolean;
        transforms3d: boolean;
        transitions: boolean;
    };
    browser: {
        ie8: boolean;
        ie10: boolean;
    };
    activeIndex: number;
    activeLoopIndex: number;
    activeLoaderIndex: number;
    previousIndex: number;
    swipeNext(internal?: boolean): boolean;
    swipePrev(internal?: boolean): boolean;
    swipeReset(): boolean;
    swipeTo(index: number, speed?: number, runCallbacks?: boolean): boolean;
    activeSlide(): SwiperSlide;
    updateActiveSlide(index: number): void;
    touches: any;
    isTouched: boolean;
    clickedSlideIndex: number;
    clickedSlide: SwiperSlide;
    wrapperTransitionEnd(callback: () => void, permanent: boolean): void;
    destroy(deleteInstance: boolean, cleanupStyles: boolean): void;
    reInit(forceCalcSlides?: boolean): void;
    resizeFix(reInit?: boolean): void;
    autoplay: boolean;
    startAutoplay(): void;
    stopAutoplay(): void;
    getWrapperTranslate(axis: string): number;
    setWrapperTranslate(x: number, y: number, z: number): void;
    setWrapperTransition(duration: any): void;
    slides: SwiperSlide[];
    slidePrev(runCallbacks?: boolean, speed?: number): void;
    slideNext(runCallbacks?: boolean, speed?: number): void;
    slideTo(index: number, speed?: number, runCallbacks?: boolean): void;
    update(updateTranslate?: boolean): void;
    onResize(): void;
    detachEvents(): void;
    attachEvents(): void;
    appendSlide(slides: HTMLElement | string | string[]): void;
    prependSlide(slides: HTMLElement | string | string[]): void;
    removeSlide(slideIndex: number): void;
    removeAllSlides(): void;
    lockSwipeToNext(): void;
    unlockSwipeToNext(): void;
    lockSwipeToPrev(): void;
    unlockSwipeToPrev(): void;
    lockSwipes(): void;
    unlockSwipes(): void;
    disableMousewheelControl(): void;
    enableMousewheelControl(): void;
    disableKeyboardControl(): void;
    enableKeyboardControl(): void;
    disableTouchControl(): void;
    enableTouchControl(): void;
    unsetGrabCursor(): void;
    setGrabCursor(): void;
    plugins?: {
        debugger?(swiper: any, params: any): void;
    };
}
