import { ReplaySubject } from 'rxjs/ReplaySubject';
import { Observable } from 'rxjs/Observable';
import { MaAuthService } from '../auth/auth.service';
import { MaApiCartService } from '../../modules/api-module/api-cart/api-cart.service';
import { MaApiProductVariation } from '../../modules/api-module/api-product';
import { MaApiCartListResponse, MaApiSetItemData, MaApiSetItemResponse, MaApiCartListData, MaApiSetDeliveryData, MaApiSetPaymentData, MaApiDeliveryOption, MaApiMakeOrderResponse, MaApiCartProduct, MaApiMakeOrderData } from '../../modules/api-module/api-cart/api-cart.model';
import { MaApiResponse } from '../../modules/api-module';
export declare class MaCartService {
    protected apiCartService: MaApiCartService<MaApiCartListResponse<any>, MaApiSetItemData, MaApiSetItemResponse<any>, MaApiSetDeliveryData, MaApiResponse, MaApiSetPaymentData, MaApiMakeOrderData<any>, MaApiMakeOrderResponse>;
    protected authService: MaAuthService;
    protected sidebarCartOpenSubject$: ReplaySubject<boolean>;
    protected cartListSubject$: ReplaySubject<MaApiCartListResponse<any>>;
    protected relatedProductsData$: ReplaySubject<MaApiProductVariation<any, any, any>[]>;
    protected cartList: MaApiCartListResponse<any>;
    protected cartId: number;
    constructor(apiCartService: MaApiCartService<MaApiCartListResponse<any>, MaApiSetItemData, MaApiSetItemResponse<any>, MaApiSetDeliveryData, MaApiResponse, MaApiSetPaymentData, MaApiMakeOrderData<any>, MaApiMakeOrderResponse>, authService: MaAuthService);
    getCartList(): Observable<MaApiCartListResponse<any>>;
    refreshCartList(): void;
    protected updateCartList(data: MaApiCartListResponse<any>): void;
    watchCartList(): Observable<MaApiCartListResponse<any>>;
    getProduct(id: string): MaApiCartProduct<any, any, any, any>;
    getCartData(): MaApiCartListData<any, any, any, any, any, any, any>;
    getItemsCount(): number;
    getCartId(): number;
    watchSidebarCartOpen(): Observable<boolean>;
    watchRelatedProducts(): Observable<MaApiProductVariation<any, any, any>[]>;
    protected updateRelatedProducts(response: MaApiSetItemResponse<any>): void;
    addElement(productId: number): Observable<MaApiSetItemResponse<any>>;
    removeElement(productId: number): Observable<MaApiSetItemResponse<any>>;
    clear(): void;
    changeQuantity(productId: number, quantity: number): Observable<MaApiSetItemResponse<any>>;
    changeSize(oldProductId: number, newProductId: number, quantity: number): Observable<MaApiSetItemResponse<any>>;
    setDelivery(id: number, parcel?: string): void;
    getSelectedDeliveryOption(): MaApiDeliveryOption<any, any>;
    isDeliveryInpost(): boolean;
    isSalonDelivery(): boolean;
    setPayment(type: string): void;
    makeOrder(makeOrderData: any): Observable<MaApiMakeOrderResponse>;
    validateCart(): boolean;
}
