import { ReplaySubject } from 'rxjs/ReplaySubject';
import { Observable } from 'rxjs/Observable';
import { CookieService } from 'ngx-cookie-service';
import { MaApiUserService } from '../../modules/api-module/api-user/api-user.service';
import { MaApiUserAuthorizeData, MaApiUserAuthorizeResponse, MaApiUserData, MaApiUserRegisterData, MaApiUserRegisterResponse, MaApiUserAuthorizeResponseData, MaApiUserRemindData, MaApiFbAuthorizeData, MaApiFbAuthorizeResponse, MaApiUserTokenResponse, MaApiUserChangePasswordData, MaApiUserAddressResponse, MaApiUserOrderListResponse } from '../../modules/api-module/api-user/api-user.model';
import { MaApiResponse } from '../../modules/api-module';
export declare const MaTokenKeyName = "session-token";
export declare class MaAuthService {
    protected apiUserService: MaApiUserService<MaApiUserAuthorizeData, MaApiUserAuthorizeResponse<any>, MaApiFbAuthorizeData, MaApiFbAuthorizeResponse, MaApiUserRegisterData, MaApiUserRegisterResponse, MaApiUserOrderListResponse<any>, MaApiUserAddressResponse<any, any>, MaApiUserChangePasswordData, MaApiUserTokenResponse<any>, MaApiUserRemindData, MaApiResponse>;
    protected cookieService: CookieService;
    protected authorized: boolean;
    protected authorizeSubject$: ReplaySubject<boolean>;
    protected userData: MaApiUserData;
    protected userDataSubject$: ReplaySubject<MaApiUserData>;
    protected token: string;
    constructor(apiUserService: MaApiUserService<MaApiUserAuthorizeData, MaApiUserAuthorizeResponse<any>, MaApiFbAuthorizeData, MaApiFbAuthorizeResponse, MaApiUserRegisterData, MaApiUserRegisterResponse, MaApiUserOrderListResponse<any>, MaApiUserAddressResponse<any, any>, MaApiUserChangePasswordData, MaApiUserTokenResponse<any>, MaApiUserRemindData, MaApiResponse>, cookieService: CookieService);
    populate(clear?: boolean): Promise<boolean>;
    protected setUserData(data: MaApiUserAuthorizeResponseData): void;
    authorize(auth: MaApiUserAuthorizeData): Observable<MaApiUserAuthorizeResponse<any>>;
    fbAuthorize(auth: MaApiFbAuthorizeData): Observable<MaApiFbAuthorizeResponse>;
    register(register: MaApiUserRegisterData): Observable<MaApiUserRegisterResponse>;
    remind(remind: MaApiUserRemindData): Observable<MaApiResponse>;
    protected setAuthorized(auth: boolean): void;
    watchAuthorized(): Observable<boolean>;
    isAuthorized(): boolean;
    watchUserData(): Observable<MaApiUserData>;
    getUserData(): MaApiUserData;
    clearData(): void;
    logout(): void;
}
